import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../styles/globals.css";
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
